apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialhub-argo-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: socialhub
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: github.com/Yuni-sa/social-hub-manifests
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
