apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-image
  template:
    metadata:
      labels:
        app: golang-image
    spec:
      containers:
      - name: golang-image
        image: yuni2/golang-image:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-image-service
spec:
  selector:
    app: golang-image
  ports:
  - port: 4000
    targetPort: 4000